//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.01.13 at 03:24:29 AM CAT
//
package za.co.mmagon.logger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{
    "properties"
})
@XmlRootElement(name = "LogEntry")
public class LogEntry
{

    @XmlElement(name = "Properties", required = true)
    protected Properties properties;
    @XmlAttribute(name = "datetime", required = true)
    protected XMLGregorianCalendar datetime;
    @XmlAttribute(name = "level")
    protected LogLevels level;
    @XmlAttribute(name = "class", required = true)
    protected String clazz;

    /**
     * Gets the value of the properties property.
     *
     * @return
     *         possible object is
     *         {@link Properties }
     *
     */
    public Properties getProperties()
    {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value
     *              allowed object is
     *              {@link Properties }
     *
     */
    public void setProperties(Properties value)
    {
        this.properties = value;
    }

    /**
     * Gets the value of the datetime property.
     *
     * @return
     *         possible object is
     *         {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatetime()
    {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     *
     * @param value
     *              allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setDatetime(XMLGregorianCalendar value)
    {
        this.datetime = value;
    }

    /**
     * Gets the value of the level property.
     *
     * @return
     *         possible object is
     *         {@link LogLevels }
     *
     */
    public LogLevels getLevel()
    {
        return level;
    }

    /**
     * Sets the value of the level property.
     *
     * @param value
     *              allowed object is
     *              {@link LogLevels }
     *
     */
    public void setLevel(LogLevels value)
    {
        this.level = value;
    }

    /**
     * Gets the value of the clazz property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getClazz()
    {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     *
     * @param value
     *              allowed object is
     *              {@link String }
     *
     */
    public void setClazz(String value)
    {
        this.clazz = value;
    }

}
