//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.13 at 07:27:15 PM CAT 
//


package za.co.mmagon.jwebswing.htmlbuilder.javascript.ajax.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ScriptUpdate" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *         &lt;element name="ScriptLinkUpdate" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *         &lt;element name="CSSLinkUpdate" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *         &lt;element name="CSSUpdate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HTMLUpdate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "scriptUpdate",
    "scriptLinkUpdate",
    "cssLinkUpdate",
    "cssUpdate",
    "htmlUpdate"
})
@XmlRootElement(name = "compUpdate")
public class CompUpdate {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "ScriptUpdate", required = true)
    protected List<String> scriptUpdate;
    @XmlElement(name = "ScriptLinkUpdate", required = true)
    protected List<String> scriptLinkUpdate;
    @XmlElement(name = "CSSLinkUpdate", required = true)
    protected List<String> cssLinkUpdate;
    @XmlElement(name = "CSSUpdate", required = true)
    protected String cssUpdate;
    @XmlElement(name = "HTMLUpdate", required = true)
    protected String htmlUpdate;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the scriptUpdate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scriptUpdate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScriptUpdate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getScriptUpdate() {
        if (scriptUpdate == null) {
            scriptUpdate = new ArrayList<String>();
        }
        return this.scriptUpdate;
    }

    /**
     * Gets the value of the scriptLinkUpdate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scriptLinkUpdate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScriptLinkUpdate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getScriptLinkUpdate() {
        if (scriptLinkUpdate == null) {
            scriptLinkUpdate = new ArrayList<String>();
        }
        return this.scriptLinkUpdate;
    }

    /**
     * Gets the value of the cssLinkUpdate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cssLinkUpdate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCSSLinkUpdate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCSSLinkUpdate() {
        if (cssLinkUpdate == null) {
            cssLinkUpdate = new ArrayList<String>();
        }
        return this.cssLinkUpdate;
    }

    /**
     * Gets the value of the cssUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSSUpdate() {
        return cssUpdate;
    }

    /**
     * Sets the value of the cssUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSSUpdate(String value) {
        this.cssUpdate = value;
    }

    /**
     * Gets the value of the htmlUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHTMLUpdate() {
        return htmlUpdate;
    }

    /**
     * Sets the value of the htmlUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHTMLUpdate(String value) {
        this.htmlUpdate = value;
    }

}
